#eureka:
 # client:
    
    ### IL DISCOVERY SERVER NON DEVE REGISTRARSI COL DISCOVERY PERCHE' E' 
    ### ESSO STESSO IL DISCOVERY
    
  #  fetch-registry: false
   # register-with-eureka: false
#server:
 # port: 8761
#spring:
 #config:
  # import:
   # - optional:configserver:http://localhost:8088
 #application:
  #name: discovery
 #cloud:
  #config:
   #import-check:
    #enabled: false