eureka:
   client:
      service-url:
         defaultZone: ${eureka_other_server_url}
      fetch-registry: false
      register-with-eureka: false
spring:
   #cloud:
    #config:
     #import-check:
      #enabled: false
   config:
    import:
    - optional:configserver:http://localhost:8088
   application:
      name: discovery
server:
   port: ${app_port}